name: CI

on: [push, pull_request]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install ltd-conveyor

      - name: Build documentation
        run: make html

      - name: Upload to LSST the Docs
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product developer --gh --dir _build/html
