# This workflow runs on a weekly basis and validates the integrity of the
# build and links.

name: Weekly CI

on:
  schedule:
    - cron: "0 4 * * MON"

jobs:
  linkcheck:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Run linkcheck
        run: make linkcheck

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Run HTML build
        run: make html
